### PR TITLE
Upgrades

### PR DESCRIPTION
**Pull request by Ponyboy47**
- Removed manual C-based `wait`ing (These often peg a CPU at 100%)
- Transition from a `Pattern` `enum` to a `struct`
  - No need for huge switch statements, makes adding new patterns simpler
- Added `Decodable` conformance to `Pattern`
  - So that people can easily create and load their own patterns (or the existing patterns from [sindresorhus/cli-spinners](https://github.com/sindresorhus/cli-spinners/blob/master/spinners.json))
- Don't import all of Foundation (since it's big and only is getting bigger)
- New tests for new functionality
- Created a `Patterns` struct for loading multiple patterns from a single file

### CODE REVIEW

**Comment by kiliankoe** [comment]
Wow, thanks for the PR! All of this sounds fantastic, I love the custom pattern decoding 👍 Give me a bit to take a look through this before I merge, but huge thanks anyways!

> Don't import all of Foundation (since it's big and only is getting bigger)

I'm pretty sure an `import Foundation` only pollutes the namespace, but importing less than that has no implications regarding the size of the resulting binary. Iirc this is a plan for the future, but nothing the Swift compiler does currently, although it would be fantastic, no doubt.

**Comment by Ponyboy47** [comment]
I actually didn't know that about imports and you are indeed correct that it really just pollutes the namespace. Since I hadn't heard that before I went looking and found [this blog post](https://thoughtbot.com/blog/swift-imports) which contains the statement:
```
As far as performance and binary size goes, any unused symbols are already optimized out of the final binary by the Swift compiler.
```
You learn something new every day!

The original spinner repo you reference has added quite a few new spinners to their spinners.json and originally I just wanted to get the new spinners added here. After checking out the `Pattern` enum I didn't think it would be that simple to add a bunch of new ones with it that way since you'd have to mess around with two separate huge switch statements for each new spinner. So I got to thinking about letting people (\*cough\* me) include this package to create their own spinners at compile time (thus the `SpinnerPattern` protocol) and it just kind of snowballed from there until I got it decoding spinners from files at runtime. Now I really wouldn't even need to use the `SpinnerPattern` protocol to get the new spinners I wanted.

**Comment by kiliankoe** [comment]
Huh, that's interesting. And good to know 👍

**Review by kiliankoe — APPROVED** [review]
LGTM, thanks again!

**Comment by kiliankoe** [comment]
Just tagged this as 0.4.0.

**Pull request merged**
